import React, { useEffect, useMemo, useRef, useState } from 'react';
import { CalendarDays, CheckCircle2, Clock, Mail, MapPin, Send, UserRound, X } from 'lucide-react';
import type { Club } from '../types';
import useModalScrollLock from '../hooks/useModalScrollLock';

export default function TrainingRegistrationModal({ clubs, isOpen, onClose }: { clubs: Club[]; isOpen: boolean; onClose: () => void }) {
  const activeClubs = useMemo(() => clubs.filter(c => c.status !== false), [clubs]);
  const [fullName, setFullName] = useState(''); const [email, setEmail] = useState('');
  const [clubId, setClubId] = useState(''); const [message, setMessage] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [result, setResult] = useState<{type:'success'|'error';text:string}|null>(null);
  const panelRef = useRef<HTMLDivElement>(null);
  const club = activeClubs.find(c => c.id === clubId);
  useModalScrollLock(isOpen, onClose);
  useEffect(() => { if (!isOpen) return; const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()}; window.addEventListener('keydown',fn); setTimeout(()=>panelRef.current?.querySelector<HTMLInputElement>('input')?.focus(),0); return()=>window.removeEventListener('keydown',fn); }, [isOpen]);
  const submit=async(e:React.FormEvent)=>{e.preventDefault(); if(submitting)return; setSubmitting(true);setResult(null);try{const r=await fetch('/api/training-registrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName,email,clubId,message})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||'Không thể gửi đăng ký lúc này.');setResult({type:'success',text:'\u0110\u0103ng k\u00fd th\u00e0nh c\u00f4ng! Form s\u1ebd t\u1ef1 \u0111\u00f3ng.'});window.setTimeout(()=>{setFullName('');setEmail('');setClubId('');setMessage('');setResult(null);onClose()}, 1800)}catch(x){setResult({type:'error',text:x instanceof Error?x.message:'Không thể gửi đăng ký.'})}finally{setSubmitting(false)}};
  if(!isOpen)return null;
  const input='box-border h-11 min-w-0 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-3 text-sm font-semibold normal-case outline-none transition focus:border-[#0054A6] focus:bg-white focus:ring-4 focus:ring-blue-100';
  return <div className="fixed inset-0 z-[100] flex items-center font-sans justify-center bg-slate-950/55 p-3 backdrop-blur-[3px] sm:p-5" role="dialog" aria-modal="true" translate="no" aria-labelledby="training-registration-title" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}>
    <div ref={panelRef} className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-[1.75rem] border border-white/70 bg-white shadow-2xl">
      <div className="relative overflow-hidden bg-gradient-to-br from-[#0054A6] to-[#00366e] px-5 py-5 text-white sm:px-7"><div className="absolute -right-8 -top-10 h-32 w-32 rounded-full bg-[#FFF200]/15"/><button type="button" onClick={onClose} aria-label="Đóng form đăng ký" className="absolute right-4 top-4 flex h-9 w-9 items-center justify-center rounded-full border border-white/20 bg-white/10 hover:bg-white/20"><X className="h-5 w-5"/></button><span className="mb-2 inline-flex rounded-full bg-[#FFF200] px-2.5 py-1 text-[9px] font-black uppercase tracking-widest text-[#0054A6]">Đăng ký tập luyện</span><h2 id="training-registration-title" className="pr-10 text-xl font-black uppercase sm:text-2xl">Bắt đầu hành trình Vovinam</h2><p className="mt-1.5 text-xs text-blue-100">Chọn điểm tập phù hợp và chờ xác nhận qua email.</p></div>
      <form onSubmit={submit} className="space-y-4 p-5 sm:p-7"><div className="grid grid-cols-1 gap-4 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
        <label className="min-w-0 space-y-1.5 text-xs font-black uppercase text-slate-600">Họ và tên <span className="text-rose-500">*</span><span className="relative block"><UserRound className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input required maxLength={100} value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Nguyễn Văn A" className={input}/></span></label>
        <label className="min-w-0 space-y-1.5 text-xs font-black uppercase text-slate-600">Gmail / Email <span className="text-rose-500">*</span><span className="relative block"><Mail className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input required type="email" maxLength={160} value={email} onChange={e=>setEmail(e.target.value)} placeholder="ten@gmail.com" className={input}/></span></label></div>
        <label className="block space-y-1.5 text-xs font-black uppercase text-slate-600">Câu lạc bộ <span className="text-rose-500">*</span><select required value={clubId} onChange={e=>setClubId(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold normal-case text-slate-700 outline-none focus:border-[#0054A6] focus:ring-4 focus:ring-blue-100"><option value="">— Chọn câu lạc bộ muốn tập —</option>{activeClubs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
        {club&&<div className="grid gap-2 rounded-2xl border border-emerald-200 bg-emerald-50/80 p-4 text-xs text-slate-700 sm:grid-cols-2"><div className="flex gap-2"><CalendarDays className="h-4 w-4 text-emerald-600"/><span><strong className="block text-emerald-800">Ngày tập</strong>{club.trainingDays||'Đang cập nhật'}</span></div><div className="flex gap-2"><Clock className="h-4 w-4 text-emerald-600"/><span><strong className="block text-emerald-800">Giờ tập</strong>{club.trainingHours||'Đang cập nhật'}</span></div><div className="flex gap-2 sm:col-span-2"><MapPin className="h-4 w-4 shrink-0 text-emerald-600"/><span><strong className="block text-emerald-800">Địa chỉ</strong>{club.address||'Đang cập nhật'}</span></div></div>}
        <label className="block space-y-1.5 text-xs font-black uppercase text-slate-600">Nội dung <span className="font-semibold normal-case text-slate-400">(không bắt buộc)</span><textarea maxLength={1000} rows={3} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Điều bạn muốn trao đổi thêm…" className="w-full resize-none rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm font-medium normal-case outline-none focus:border-[#0054A6] focus:ring-4 focus:ring-blue-100"/></label>
        {result&&<div className={`flex gap-2 rounded-xl border p-3 text-xs font-bold ${result.type==='success'?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-rose-200 bg-rose-50 text-rose-700'}`}>{result.type==='success'&&<CheckCircle2 className="h-4 w-4 shrink-0"/>}<span>{result.text}</span></div>}
        <button disabled={submitting} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#0054A6] to-[#0071cf] text-sm font-black uppercase tracking-wide text-white shadow-lg disabled:opacity-60"><Send className="h-4 w-4"/>{submitting?'Đang gửi…':'Gửi đăng ký tập luyện'}</button>
      </form></div></div>;
}
