const createSearchEmbedUrl = (query: string, center?: string) => {
  const params = new URLSearchParams({
    q: query,
    t: '',
    z: '17',
    ie: 'UTF8',
    iwloc: '',
    output: 'embed'
  });
  if (center) params.set('ll', center);
  return `https://maps.google.com/maps?${params.toString()}`;
};

const createCenteredCoordinateEmbedUrl = (coordinates: string) => {
  const params = new URLSearchParams({ ll: coordinates, t: '', z: '17', ie: 'UTF8', output: 'embed' });
  return `https://maps.google.com/maps?${params.toString()}`;
};
const decodeHtmlEntities = (value: string) =>
  value
    .replace(/&amp;/gi, '&')
    .replace(/&#38;/gi, '&')
    .replace(/&quot;/gi, '"');

const getSearchCoordinates = (value: string | null) => {
  const match = String(value || '').trim().match(/^(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)$/);
  return match ? `${match[1]},${match[2]}` : '';
};
const getCoordinates = (value: string) => {
  // A shared Maps URL can contain both a shifted viewport and the real marker.
  // Prefer the marker so it appears in the visual center of the embed.
  const placeMatch = value.match(/!3d(-?\d+(?:\.\d+)?)!4d(-?\d+(?:\.\d+)?)/);
  if (placeMatch) return `${placeMatch[1]},${placeMatch[2]}`;

  const viewportMatch = value.match(/@(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)/);
  if (viewportMatch) return `${viewportMatch[1]},${viewportMatch[2]}`;

  return '';
};

/**
 * Accepts the complete Google Maps iframe HTML, an exact /maps/embed URL,
 * or a full Google Maps URL containing coordinates. Old generated search
 * URLs are intentionally rebuilt from the latest form fields so a stale
 * address can never override the address currently saved by an admin.
 */
export const buildGoogleMapsEmbedUrl = (
  configuredUrl: string | undefined,
  fallbackQuery: string
) => {
  const normalizedFallback = fallbackQuery.trim() || 'Việt Nam';
  const fallback = createSearchEmbedUrl(normalizedFallback);
  let rawUrl = decodeHtmlEntities(String(configuredUrl || '').trim());
  if (!rawUrl) return fallback;

  const iframeSource = rawUrl.match(/src\s*=\s*["']([^"']+)["']/i)?.[1];
  if (iframeSource) rawUrl = decodeHtmlEntities(iframeSource);

  try {
    const parsed = new URL(rawUrl);
    const hostname = parsed.hostname.toLowerCase();
    const isGoogleMapsHost =
      hostname === 'maps.google.com' ||
      hostname === 'www.google.com' ||
      hostname === 'google.com' ||
      hostname.endsWith('.google.com');

    if (!isGoogleMapsHost) return fallback;

    // Coordinate queries render the selected marker in the center rather than
    // inheriting a viewport shifted by Google's place-information panel.
    if (parsed.pathname.includes('/maps/embed')) {
      const coordinates = getCoordinates(rawUrl);
      return coordinates ? createCenteredCoordinateEmbedUrl(coordinates) : parsed.href;
    }

    const placeId = parsed.searchParams.get('query_place_id');
    if (placeId) return createSearchEmbedUrl(`place_id:${placeId}`);

    const coordinates = getCoordinates(rawUrl) ||
      getSearchCoordinates(parsed.searchParams.get('ll')) ||
      getSearchCoordinates(parsed.searchParams.get('q'));
    if (coordinates) return createCenteredCoordinateEmbedUrl(coordinates);

    // An output=embed search URL generated by an older version is not an
    // exact place reference. Rebuild it from the latest place/address fields.
    return fallback;
  } catch {
    return fallback;
  }
};
